name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: ^8.15.5
      - uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          node-version: 18
      - name: Install dependencies
        run: pnpm install
      - name: Run build
        run: pnpm run build
      - name: Run tests
        run: pnpm run test
